### ISSUE TITLE
'revisions' - not 'allRevisions'

### ISSUE THREAD

**Issue by odungern** [GfSE/SpecIF-OpenAPI#10]
@oalt: we need to change the endpoint name as indicated in the title. We say also GET ../resources when we want to get all resources (or a filtered list according to the query string). See oskar's branch,

Also, there are still quite some differences between the branches, e.g. capital initials in the main branch.

**Comment by oalt** [comment]
I will take a look and change it.

**Comment by odungern** [comment]
implemented with v1.1
